name: Cypress E2E Tests

on:
  push:
    branches: [main, cypress-ci]
  pull_request:
    branches: [main, cypress-ci]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout do código
        uses: actions/checkout@v4

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Instalar dependências do monorepo
        run: npm install

      - name: 🚀 Iniciar app (client + server)
        run: npm run start:ci &
        env:
          CI: true

      - name: ⏳ Aguardar aplicação estar pronta
        uses: jakejarvis/wait-for-netlify-action@v1
        with:
          url: http://localhost:3000
          timeout: 60

      - name: 🧪 Rodar testes E2E do Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:ci
          wait-on: http://localhost:3000
          wait-on-timeout: 60
          browser: chrome
